### ISSUE TITLE
Agile project plan document

### ISSUE THREAD

**Issue by sofiecmf** [IL2232-HT2022-HIL/IL2232-HT2022-HIL#12]
**Assignment description:**

Your agile project plan should include the following: 
 
- [x] A background section with a short description of your project 
- [x] The project goals (as specific as you can). If the reason you choose an agile approach 
is that there are no clear goals, make an effort to instead formulate the purpose of the 
project, how your work is going to be evaluated and by whom.  
- [x] A description of how you are going to work in the project including the following: 
o How long will your iterations/sprints be? 
o On what dates will you have your sprint reviews and retrospectives? 
o When and how will you plan each sprint? 
o How will you divide the work between you?  
o How will you review your work and get feedback after each sprint? 
o How will you review and improve your work process after each sprint? 
- [x] A description of how you will communicate with each other and other stakeholders 
- [x] Dates for submissions of status updates and lessons learned report 
- [x] Planned format of the status updates 
- [x] Your first sprint plan (as long as it is readable, any format is ok, including photos of 
post-it-notes, a screenshot of a digital plan etc.) 
- [x] Anything else that you feel is relevant and help you get an overview of your project 
and way of working 
 
So, instead of specifying exactly what you will be doing in the different process phases, your 
focus will be to specify your work place. However, just as in a traditional project plan, be as 
precise and specific as you can. Please book a team guidance session if you want to discuss 
anything.  
 
All submissions should include:  
 
- [x] Team name 
- [x] Names of the team members 
- [x] Date 
- [x] Name of submission

**Comment by sofiecmf** [comment]
Here is a link to the document:
https://www.overleaf.com/6473542294thhbrkcfmmqb

**Comment by sofiecmf** [comment]
What needs to be done?

- [x] Write background
- [x] Write goals
- [x] Write about how we are going to work
- [x] Insert submission deadlines
- [x] Give description of format for status updates
- [x] Insert image of first sprint plan

**Comment by sofiecmf** [comment]
Final steps:

- [x] Upload the pdf here and tag Matthias to review 
- [ ] Update document according to feedback
- [ ] Submit to Canvas

**Comment by sofiecmf** [comment]
Hi @matthiasthomasbecker,
Now we have completed a first draft of our project plan. It is a bit lightweight, but it contains all parts required by the course responsible. Do you want us to change or add anything?

[IL2232_Agile_project_plan-3.pdf](https://github.com/IL2232-HT2022-HIL/IL2232-HT2022-HIL/files/9707014/IL2232_Agile_project_plan-3.pdf)

**Comment by matthiasthomasbecker** [comment]
Hi, 
Thanks for sending the project plan draft. 
There are some parts that I suggest you revisit before submission. 

- The deliverables look good but I am missing an explicit deliverable for the different modules to simulate sensors and actuators on the platform. I would not say it is part of the control server itself, instead, the control server receives requests and then interacts with the sensor/actuator simulation modules. 
- I suggest labelling the deliverables D1, D2, etc. to make traceability easier. 
- Sec. 4B mentions milestones but they are not described or discussed earlier. Please add milestones to the plan, preferably using a Gant-Chart to show how different tasks depend on each other etc.

**Comment by sofiecmf** [comment]
Thank you for sharing your feedback! We will update the draft this afternoon to include your proposed edits

**Comment by sofiecmf** [comment]
Agile project plan v.2



[IL2232_Agile_project_plan-4.pdf](https://github.com/IL2232-HT2022-HIL/IL2232-HT2022-HIL/files/9725735/IL2232_Agile_project_plan-4.pdf)

**Comment by matthiasthomasbecker** [comment]
Hi,
thanks a lot! From my side, it looks ok now.
